# GitHub Sponsors Configuration
# These are supported funding model platforms

github: travisjneuman
# patreon: # Replace with your Patreon username if applicable
# open_collective: # Replace with your Open Collective username if applicable
# ko_fi: # Replace with your Ko-fi username if applicable
# tidelift: # Format: npm/package-name
# community_bridge: # Replace with a single Community Bridge project-name
# liberapay: # Replace with your Liberapay username if applicable
# issuehunt: # Replace with your IssueHunt username if applicable
# otechie: # Replace with your Otechie username if applicable
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name
# custom: ["https://www.buymeacoffee.com/travisjneuman"]
