#!/bin/bash
# Sync .claude toolkit counts into README.md
# Reads from ~/.claude/counts.json (generated by update-counts.sh)

COUNTS_FILE="$HOME/.claude/counts.json"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
README="$SCRIPT_DIR/../README.md"

if [ ! -f "$COUNTS_FILE" ]; then
  echo "Error: $COUNTS_FILE not found. Run ~/.claude/scripts/update-counts.sh first."
  exit 1
fi

# Convert to Windows path for Node.js if on Windows (Git Bash)
if command -v cygpath &>/dev/null; then
  NODE_PATH="$(cygpath -w "$COUNTS_FILE")"
else
  NODE_PATH="$COUNTS_FILE"
fi

# Parse counts
read_count() {
  node -e "const c=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'));console.log(c['$1'])" "$NODE_PATH"
}

SKILLS=$(read_count skills)
AGENTS=$(read_count agents)
REPOS=$(read_count repos)
MARKET=$(read_count marketplaceSkillsDisplay)

if [ -z "$SKILLS" ] || [ -z "$REPOS" ]; then
  echo "Error: Failed to parse counts from $COUNTS_FILE"
  exit 1
fi

echo "Syncing counts: $SKILLS skills, $AGENTS agents, $REPOS repos, $MARKET marketplace"

# Update blockquote line
sed -i "s|> [0-9]\+ custom skills\. [0-9]\+ specialized agents\. [0-9,]\+.* marketplace skills\. Open source\.|> $SKILLS custom skills. $AGENTS specialized agents. $MARKET marketplace skills. Open source.|" "$README"

# Update stats line
sed -i "s|\*\*[0-9]\+ skills\*\* · \*\*[0-9]\+ agents\*\* · \*\*[0-9]\+ repos\*\* · \*\*[0-9,]\+.* marketplace skills\*\*|**$SKILLS skills** · **$AGENTS agents** · **$REPOS repos** · **$MARKET marketplace skills**|" "$README"

# Update highlights line marketplace integrations count
sed -i "s|[0-9]\+ open-source marketplace integrations|$REPOS open-source marketplace integrations|" "$README"

# Update table card
sed -i "s|🤖 [0-9]\+ skills · [0-9]\+ agents<br/>[0-9,]\+.* marketplace|🤖 $SKILLS skills · $AGENTS agents<br/>$MARKET marketplace|" "$README"

echo "Done. Review changes with: git diff README.md"
